# ===============================
# Netlify Configuration for React + EmailJS
# ===============================

[build]
  command = "npm run build"
  publish = "build"

  # Environment setup (must be single-line in TOML)
  environment = { NODE_VERSION = "18", SECRETS_SCAN_OMIT_KEYS = "REACT_APP_PUBLIC_KEY,REACT_APP_SERVICE_ID,REACT_APP_TEMPLATE_ID" }

# ===============================
# Redirects (for React Router)
# ===============================

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ===============================
# Optional Build Image override
# Uncomment if “Noble” image gives errors
# [build.image]
#   id = "ubuntu-22.04"
# ===============================
